app:
  name: "Service"
  mode: "dev"
  port: 
log:
  level: "debug"
  filename: "Service"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: ""
  port: 
  user: ""
  password: ""
  dbname: ""
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: ""
  port: 
  password: ""
  db: 0
  poll_size: 100
