name: "Service"
mode: "dev"
version: "v0.0.1"
start_time: "2022-02-01"
port: 8082

auth:
#  定义token过期时间
  jwt_expire: 8760


log:
  level: "debug"
  filename: "Service.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: ""
  port: 63916
  user: "root"
  password: ""
  dbname: ""
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: ""
  port: 24531
  password: ""
  db: 0
  poll_size: 100
