name: "service"
mode: "dev"
version: "v0.0.1"
start_time: "2022-02-01"
port: 8082

auth:
  #  定义token过期时间
  jwt_expire: 8760


log:
  level: "debug"
  filename: "Service.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: ""
  port: 
  user: "root"
  password: ""
  dbname: "decentralized_social_platforms"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: ""
  port: 
  password: ""
  db: 0
  poll_size: 100
